services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "11503:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: fastapi_image_classification
    volumes:
      - ~/postgres/data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "11501:9000"
      - "11502:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"